name: Java CI/CD with Maven and Secure Config

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Create config.properties
      run: |
        {
          echo "db.url=${{ secrets.DB_URL }}"
          echo "db.username=${{ secrets.DB_USERNAME }}"
          echo "db.password=${{ secrets.DB_PASSWORD }}"
          echo "api.key=${{ secrets.API_KEY }}"
        } > src/main/resources/config.properties
      shell: bash

    - name: Build with Maven
      run: mvn clean package

    - name: Rename WAR file
      run: mv target/*.war target/ROOT.war

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} 'rm -f /opt/tomcat/webapps/ROOT.war'
        scp -o StrictHostKeyChecking=no -i private_key target/ROOT.war ${USER}@${HOST}:/opt/tomcat/webapps/
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} 'rm -rf /opt/tomcat/webapps/ROOT'

    - name: Clean up
      run: rm -f src/main/resources/config.properties
